name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package -DskipTests --file backend/pom.xml

    - name: List artifact 
      run: ls -lia backend/
  
    - name: Log into GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }} 
        #added
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: backend/
        push: true
        tags: ghcr.io/${{ github.repository }}/my-image:${{ github.sha }}
